source "$SP/dog.sh"
echo "=== domains: i18n, redirects, flags, configs ==="
I="$B/v1/hooks/i18n"; R="$B/v1/hooks/redirects"; FL="$B/v1/hooks/flags"; C="$B/v1/hooks/configs"
chk "fr inherits from en"       "$(curl -s "$I?locale=fr" | python3 -c 'import json,sys;e=json.load(sys.stdin)["entries"];print(e["nav.home"]+"/"+e["nav.about"])')" "Accueil/About us"
chk "Accept-Language q-weights" "$(curl -s "$I" -H 'Accept-Language: de;q=1.0,fr;q=0.5' | python3 -c 'import json,sys;print(json.load(sys.stdin)["locale"])')" "fr"
chk "interpolation"             "$(curl -s "$I?locale=en&key=cta.hi&vars=%7B%22name%22%3A%22Ada%22%7D" | python3 -c 'import json,sys;print(json.load(sys.stdin)["value"])')" "Hi, Ada"
chk "missing key is queued"     "$(curl -s "$I?locale=fr&key=dog.absent" >/dev/null; a "$B/v1/store/i18n/missing" | python3 -c 'import json,sys;print(json.load(sys.stdin)["total"]>=1)')" "True"
ET=$(curl -s -D- -o /dev/null "$I?locale=en" | grep -i '^etag' | tr -d '\r' | cut -d' ' -f2)
chk "bundle ETag 304"           "$(curl -s -o /dev/null -w '%{http_code}' -H "If-None-Match: $ET" "$I?locale=en")" "304"
chk "redirect issues a 301"     "$(curl -s -o /dev/null -w '%{http_code}' "$R?path=/dog-old")" "301"
chk "redirect Location"         "$(curl -s -D- -o /dev/null "$R?path=/DOG-OLD/" | grep -i '^location' | tr -d '\r' | cut -d' ' -f2)" "/dog-new"
chk "query preserved"           "$(curl -s -D- -o /dev/null "$R?path=%2Fdog-old%3Futm%3Dx" | grep -i '^location' | tr -d '\r' | cut -d' ' -f2)" "/dog-new?utm=x"
chk "prefix rule"               "$(curl -s -D- -o /dev/null "$R?path=/dogdocs/intro" | grep -i '^location' | tr -d '\r' | cut -d' ' -f2)" "https://docs.example.com/intro"
chk "no match is 404"           "$(curl -s -o /dev/null -w '%{http_code}' "$R?path=/nothing-here")" "404"
chk "anon sees only public"     "$(curl -s "$FL?anon=v1" | python3 -c 'import json,sys;print(",".join(sorted(json.load(sys.stdin)["flags"])))')" "dog-public,dog-rollout"
chk "flag stability"            "$(for i in 1 2 3; do curl -s "$FL?anon=stable7" | python3 -c 'import json,sys;print(json.load(sys.stdin)["flags"]["dog-rollout"])'; done | sort -u | wc -l)" "1"
chk "config by alias"           "$(curl -s "$C?alias=dogprice" | python3 -c 'import json,sys;print(json.load(sys.stdin)["slug"])')" "dog-pricing"
chk "config raw mode"           "$(curl -s "$C?alias=dogprice&raw=1" | python3 -c 'import json,sys;print(json.load(sys.stdin)["plans"][0]["price"])')" "29"
chk "config cache TTL"          "$(curl -s -D- -o /dev/null "$C?alias=dogprice" | grep -i "^cache-control" | tr -d "\r" | cut -d" " -f2-)" "public, max-age=120"
echo "   [$PASS passed, $FAIL failed]"
