source "$SP/dog.sh"
echo "=== events, cron, lock, script — live ==="
chk "events emit"        "$(aj -X POST "$B/v1/events/dog" -d '{"type":"probe","level":"warn","subject":"live"}' | python3 -c 'import json,sys;print(json.load(sys.stdin)["event"]["level"])')" "warn"
chk "events filter"      "$(a "$B/v1/events/dog?level=warn" | python3 -c 'import json,sys;print(json.load(sys.stdin)["count"]>=1)')" "True"
chk "events since"       "$(a "$B/v1/events/dog?since=1h" | python3 -c 'import json,sys;print(json.load(sys.stdin)["count"]>=1)')" "True"
chk "events stats"       "$(a "$B/v1/events/dog/stats?by=type" | python3 -c 'import json,sys;print(json.load(sys.stdin)["total"]>=1)')" "True"
chk "bad group rejected" "$(curl -s -o /dev/null -w '%{http_code}' -H "Authorization: Bearer $ADMIN" "$B/v1/events/dog/stats?by=1;DROP")" "400"
chk "streams listed"     "$(a "$B/v1/events" | python3 -c 'import json,sys;print(any(s["stream"]=="dog" for s in json.load(sys.stdin)["streams"]))')" "True"
chk "cron job listed"    "$(a "$B/v1/cron" | python3 -c 'import json,sys;print(any(j["name"]=="dogtick" for j in json.load(sys.stdin)["jobs"]))')" "True"
chk "scheduler running"  "$(a "$B/v1/cron" | python3 -c 'import json,sys;print(json.load(sys.stdin)["scheduler_running"])')" "True"
chk "cron run over HTTP" "$(aj -X POST "$B/v1/cron/dogtick/run" -d '{}' | python3 -c 'import json,sys;print(json.load(sys.stdin)["result"]["status"])')" "ok"
sleep 6
chk "scheduler fired it" "$(a "$B/v1/events/cron?type=cron.ok&subject=dogtick" | python3 -c 'import json,sys;print(json.load(sys.stdin)["count"]>=1)')" "True"
chk "script listed"      "$(a "$B/v1/script" | python3 -c 'import json,sys;print(any(s["name"]=="dogjob" for s in json.load(sys.stdin)["scripts"]))')" "True"
chk "script run + value" "$(aj -X POST "$B/v1/script/dogjob/run" -d '{}' | python3 -c 'import json,sys;print(json.load(sys.stdin)["value"]["hmac12"])')" "$(python3 -c "
import hmac,hashlib;print(hmac.new(b'k',b'm',hashlib.sha256).hexdigest()[:12])")"
chk "sandbox surface"    "$(aj -X POST "$B/v1/script/dogjob/run" -d '{}' | python3 -c 'import json,sys;print(json.load(sys.stdin)["value"]["has"])')" "auth,crypto,events,files,http,id,kv,lock,log,now,store"
chk "run history"        "$(a "$B/v1/script/dogjob/runs?limit=3" | python3 -c 'import json,sys;print(json.load(sys.stdin)["count"]>=1)')" "True"
echo "   [$PASS passed, $FAIL failed]"
